### ISSUE TITLE
portable fluid interface

### ISSUE THREAD

**Issue by MCBEModder2020** [xiewuzhiying/VS-Addition#12]
### Mod Name

create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

why only item, pls fluid too

### Issue reproduction

why only item, pls fluid too

**Comment by xiewuzhiying** [comment]
All three: items, fluids, and energy
