### ISSUE TITLE
Rendering overlay issue

### ISSUE THREAD

**Issue by Picker021** [xiewuzhiying/VS-Addition#13]
### Mod Name

i don't know which mod

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

The game crashes with this mod and Tank Tussle (changed) modpack

### Issue reproduction

just launch the game

### Logs
[crash-2024-07-16_13.24.27-client.txt](https://github.com/user-attachments/files/16244043/crash-2024-07-16_13.24.27-client.txt)

**Comment by xiewuzhiying** [comment]
Can't be sure if this is due to vs addition
