### ISSUE TITLE
Newest update breaks flywheel dependency loading, diagonalblocks library, forge kotlin, puzzles api, expandability library

### ISSUE THREAD

**Issue by Barerock** [xiewuzhiying/VS-Addition#16]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Above check for other mods is irrelevant, as it's related directly to having other mods.

### Issue reproduction

Start game with these mods and dependents installed and vs addition latest update.

Uninstalling latest update/backdating to last version resolves.

### Logs

[latest.log](https://github.com/user-attachments/files/16393506/latest.log)

**Comment by xiewuzhiying** [comment]
Unable to reproduce

**Comment by Barerock** [comment]
Weird. The fact that it affects so many mods is worrying, I'm on forge 47.2.20, perhaps that could contribute?

**Comment by brisingraerowing** [comment]
I get a similar error. Looking at the log Elytra Slot has a specific max version for the Mixin Squared library, whereas the other mods listed do not. I'm going to test without Elytra Slot and see if that works.

EDIT: The error does not occur without Elytra Slot.

**Comment by xiewuzhiying** [comment]
Is it resolved now?

**Comment by brisingraerowing** [comment]
I no longer get this with the latest Elytra Slot release.
