### ISSUE TITLE
Create does not load properly with VS-Addition installed

### ISSUE THREAD

**Issue by super4z** [xiewuzhiying/VS-Addition#17]
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

*Issue occurs on both Fabric and Forge*

The game crashes during mod loading with Create installed, on Forge loader that is not 47.2.0

Forge error screen reads as follows:
```
Create (create) has failed to load correctly
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
```

### Issue reproduction

- Install VS-Addition and dependencies in the latest Forge and Fabric loaders
- Install Create or Create Fabric respectively

### Logs

Forge log: https://mclo.gs/oQINcKJ
Forge crash report: https://mclo.gs/tEfZ1oP

Fabric log: https://mclo.gs/DEceT6d

**Comment by xiewuzhiying** [comment]
Try the latest version and see if it solves the issue
