### ISSUE TITLE
Fabric 1.20.1 Crash

### ISSUE THREAD

**Issue by aviatorrob06** [xiewuzhiying/VS-Addition#18]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Issue description

Crash on startup.

### Issue reproduction

Fabric 1.20.1 loader; only mods installed are VS, VS Additions, Fabric API, and Create Fabric

### Logs

[crash report.txt](https://github.com/user-attachments/files/16436081/crash.report.txt)

**Comment by xiewuzhiying** [comment]
I think I forgot to include mixin squared💀

**Comment by xiewuzhiying** [comment]
Fixed in latest build (not released yet)
shuangfas mistakenly added `remap=false` on some mixins, now remove them
