### ISSUE TITLE
[1.20.1] Broken with CC: Tweaked 1.112.0 (Mixin apply error)

### ISSUE THREAD

**Issue by brisingraerowing** [xiewuzhiying/VS-Addition#19]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Crash on game startup with VS Additions, CC:T 1.112.0, and dependencies installed.

### Issue reproduction

1. Install VS Additions, CC:T 1.112.0, and dependencies
2. Load game
3. Crash

### Logs

[2024-07-31-1.log](https://github.com/user-attachments/files/16443023/2024-07-31-1.log)
[debug-1.log](https://github.com/user-attachments/files/16443026/debug-1.log)

**Comment by xiewuzhiying** [comment]
Fix in the latest build, download in github action, or wait for 0.0.5d

Off topic: It is advisable to stay at 1.111.0 for the time being until most mods are compatible with 1.112.0

**Comment by SquidDev** [comment]
As a heads up, you shouldn't need most of the mixins that add custom APIs. CC:T [has a public API](https://tweaked.cc/mc-1.20.x/javadoc/dan200/computercraft/api/ComputerCraftAPI.html#registerAPIFactory(dan200.computercraft.api.lua.ILuaAPIFactory)) for adding additional APIs.
