### ISSUE TITLE
<title>前置版本错误

### ISSUE THREAD

**Issue by iamsoNewBee** [xiewuzhiying/VS-Addition#21]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

![G` 1VDNC)F}5E}ZNOY`JXM8](https://github.com/user-attachments/assets/c72600bc-14a0-4337-9817-357b4a2ac825)
已经是最新的了。。

### Issue reproduction

。

### Logs

。

**Comment by xiewuzhiying** [comment]
优选提交的时候漏改了，0.0.5c已修正
