### ISSUE TITLE
机械手无法使用除方块以外物品（如树苗，骨粉等）

### ISSUE THREAD

**Issue by iamsoNewBee** [xiewuzhiying/VS-Addition#22]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

如题

### Issue reproduction

。

### Logs

。

**Comment by xiewuzhiying** [comment]
已经有这个功能了
