### ISSUE TITLE
Crash on game loading

### ISSUE THREAD

**Issue by watermelon0guy** [xiewuzhiying/VS-Addition#23]
### Mod Name

Unknown :(

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Most recently, I successfully used the mod, but after updating the modpack, a crash occurs when the game starts. I may try to find out what the problem is, but the modpack is too big

### Issue reproduction

-

### Logs

[latest.log](https://github.com/user-attachments/files/16488643/latest.log)
[crash-2024-08-04_21.55.57-client.txt](https://github.com/user-attachments/files/16488645/crash-2024-08-04_21.55.57-client.txt)

**Comment by xiewuzhiying** [comment]
From `latest.log`, we learned that Computer Craft changed the method of Pocket Computer, causing the vs addition mixin errors.
VS Addition has been fixed, but the new version has not been released yet
Computer Craft 1.112.0 is still incompatible with some mods (in my own mod pack), it is recommended to stay at 1.111.0 for now
