### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by thetheaplant** [xiewuzhiying/VS-Addition#26]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

Fire() method does not work with autocannons.

### Issue reproduction

Construct an autocannon, attach it to a computer as a peripheral, all methods but fire() work.

**Comment by xiewuzhiying** [comment]
Basically solved, but there is still a small problem: the auto cannon on the cannon mount block, which never updates the redstone (e.g. always uses the peripheral method to control), will fire uncontrollably at intervals of about one second. Emmm, maybe I am still doing something wrong.

**Comment by xiewuzhiying** [comment]
Solved.
