### ISSUE TITLE
giving rotation to deployer crashes my game

### ISSUE THREAD

**Issue by 19PHOBOSS98** [xiewuzhiying/VS-Addition#28]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

I was using version 0.0.6b. It crashed when I tried to use a creative motor on a freshly placed deployer (no items equipped) on a VS ship. I emptied my mod folder (Except for create,eureka,clockwork,vs,kotlin,architectury and vs addition) and tried again on land with a hand crank but the same thing happened.

### Issue reproduction

-Create new world
-Assemble VS Ship
-Put down deployer on ship
-give rotation to deployer

### Logs

[latest.log](https://github.com/user-attachments/files/16642617/latest.log)
[debug.log](https://github.com/user-attachments/files/16642618/debug.log)

**Comment by 19PHOBOSS98** [comment]
as far as I tested, vs_addition-1.18.2-forge-0.0.5c+ba696de14e is the latest version that doesn't crash like this

**Comment by xiewuzhiying** [comment]
Fixed in latest build(in Github Actions)
