### ISSUE TITLE
错误！！！

### ISSUE THREAD

**Issue by QQNGK** [xiewuzhiying/VS-Addition#29]
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

版本1.18.2 下载之后与机械动力产生冲突导致机械动力错误无法进入游戏导致崩溃

### Issue reproduction

安装完模组之后显示机械动力错误

**Comment by xiewuzhiying** [comment]
需要错误报告

**Comment by QQNGK** [comment]
OK

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: xiewuzhiying ***@***.***>
发送时间: Tuesday, August 20, 2024 12:05:11 PM
收件人: xiewuzhiying/VS-Addition ***@***.***>
抄送: QQNGK ***@***.***>; Author ***@***.***>
主题: Re: [xiewuzhiying/VS-Addition] 错误！！！ (Issue #29)


需要错误报告

―
