### ISSUE TITLE
与Create不兼容

### ISSUE THREAD

**Issue by QQNGK** [xiewuzhiying/VS-Addition#30]
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

版本0.0.6c 下载之后与机械动力产生冲突导致机械动力错误无法进入游戏导致崩溃

### Issue reproduction

安装完模组之后显示机械动力错误

### Logs

[1.18.2.json](https://github.com/user-attachments/files/16673800/1.18.2.json)
[crash-2024-08-20_17.44.55-fml.txt](https://github.com/user-attachments/files/16673802/crash-2024-08-20_17.44.55-fml.txt)
[debug.log](https://github.com/user-attachments/files/16673803/debug.log)
[latest.log](https://github.com/user-attachments/files/16673806/latest.log)
[PCL 启动器日志.txt](https://github.com/user-attachments/files/16673808/PCL.txt)
[游戏崩溃前的输出.txt](https://github.com/user-attachments/files/16673810/default.txt)

**Comment by xiewuzhiying** [comment]
好吧，我没有考虑到不安装Clockwork的情况

**Comment by xiewuzhiying** [comment]
应该在0.0.6d修复（实际上是一个愚蠢的小错误😓）

**Comment by QQNGK** [comment]
所以说现在修复好了？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: xiewuzhiying ***@***.***>
发送时间: Friday, August 30, 2024 10:29:36 PM
收件人: xiewuzhiying/VS-Addition ***@***.***>
抄送: QQNGK ***@***.***>; Author ***@***.***>
主题: Re: [xiewuzhiying/VS-Addition] 与Create不兼容 (Issue #30)


应该在0.0.6d修复（实际上是一个愚蠢的小错误😓）
