### ISSUE TITLE
I'm trying to use an amulet from the hex casting mod using deployer, but it crashes

### ISSUE THREAD

**Issue by givic** [xiewuzhiying/VS-Addition#34]
### Mod Name

as far as I understand it is Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Issue description

And so I use your mod in an assembly where there is hex casting and Create, and so I had to use an amulet, however, as soon as I put the amulet in my hand and give rotation, the world immediately crashes and it is impossible to enter it. I have already contacted Create myself, but I was referred to you. I wanted the world not to end, but the amulet worked properly and was used by the hand as well as by the player

### Issue reproduction

you take your hand, you put the amulet, you let the rotation paint the world :)

### Logs

[crash-2024-08-28_03.24.10-server.txt](https://github.com/user-attachments/files/16770710/crash-2024-08-28_03.24.10-server.txt)

**Comment by givic** [comment]
and yes, deplyer crash not only when interacting with the amulet, but always when rotation is applied to it.

**Comment by xiewuzhiying** [comment]
Should be fixed in 0.0.6d
