### ISSUE TITLE
Startup error from not having CBC-MW instanned

### ISSUE THREAD

**Issue by brisingraerowing** [xiewuzhiying/VS-Addition#35]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Error occurs during startup. Due to Forge stupidity, this results in the game loading right to the main menu, then crashing if any button is clicked.

### Issue reproduction

Start game without CBC-MW installed

### Logs

[latest.log](https://github.com/user-attachments/files/16822554/latest.log)
[debug.log](https://github.com/user-attachments/files/16822555/debug.log)

**Comment by xiewuzhiying** [comment]
was fixed
