### ISSUE TITLE
为什么老版本可以让物理轴承锁定模式平滑转动,但是新版本为什么没有?

### ISSUE THREAD

**Issue by 0x132406C** [xiewuzhiying/VS-Addition#37]
老版本指的是vs_addition-1.20.1-forge-0.0.5b+a14fd8c3fe

老版本

https://github.com/user-attachments/assets/e7a569b7-c004-4c38-a95b-0152095f4d5d

新版本,也就是原版瓦尔基里

https://github.com/user-attachments/assets/06d9983e-86fd-4256-9d24-c15feec6d8fa

**Comment by xiewuzhiying** [comment]
0.0.6f 应该解决
