### ISSUE TITLE
Trackwork更新了

### ISSUE THREAD

**Issue by Yummy-cookie** [xiewuzhiying/VS-Addition#48]
[Trackwork 1.20.1-1.0.2c](https://modrinth.com/mod/trackwork/version/1.20.1-1.0.2c)
可以适配一下吗

**Comment by xiewuzhiying** [comment]
具体需要什么？

**Comment by Yummy-cookie** [comment]
> 具体需要什么？

我发现物理化，打掉方块，Trackwork的轮胎就卡地下去了，f'3+b看到

**Comment by xiewuzhiying** [comment]
没有碰撞箱所以才遁地，是正常现象。如果你将草、火把这些没有碰撞箱的方块单独物理化也会这样。

**Comment by Yummy-cookie** [comment]
我发现物物理之后，履带模型显示错误
