### ISSUE TITLE
Looks like last patch doesn't work without cbcmodernwarfare

### ISSUE THREAD

**Issue by TiusTofrie** [xiewuzhiying/VS-Addition#50]
### Mod Name

cbcmodernwarfare

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

crashes on entering the world

### Issue reproduction

install valkyrien skies, create, cc and some addons. Enter the world, then crashes.

### Logs

[latest.log](https://github.com/user-attachments/files/17398773/latest.log)
[crash-2024-10-16_18.51.33-server.txt](https://github.com/user-attachments/files/17398848/crash-2024-10-16_18.51.33-server.txt)

**Comment by xiewuzhiying** [comment]
Fixed, sorry for the oversight.
