### ISSUE TITLE
Crashes with the Fair Play edition of Xaero's Minimap

### ISSUE THREAD

**Issue by Camawama** [xiewuzhiying/VS-Addition#51]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Crashes with the Fair Play edition of Xaero's Minimap:

https://pastebin.com/jM16QKgK

### Issue reproduction

https://legacy.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/1537

**Comment by xiewuzhiying** [comment]
Fixed
