### ISSUE TITLE
CastClassException Crash with Deployer on Create Contraption

### ISSUE THREAD

**Issue by EndDragon438** [xiewuzhiying/VS-Addition#52]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Throws a CastClassException when a deployer on a moving contraption stops and is fed by a hopper.
create...GearshiftBlockEntity cannot be cast to vsaddition...IDeployerBehavior. (different modules??)

### Issue reproduction

![image](https://github.com/user-attachments/assets/5f5159c8-8ed2-44a3-96e4-4eb6afa44757)

1) Put a deployer on an arm on a mechanical bearing
2) Have a hopper feeding into a block where the deployer will be after it's rotated
3) Rotate the deployer until it's rotated (90/180/270 degrees) enough to be disassembled
4) Game crash with CastClass Exception

may have to repeat a couple times, I used a mechanical bearing with a sequenced gearshift to rotate 90 degrees at a time.
this will also crash the game again a couple times after loading the world, but it started working again after 2 attempts for me.

### Logs

CRASH REPORT: https://bytebin.lucko.me/V6oX3QEFQE
[latest.log](https://github.com/user-attachments/files/17527373/latest.log)
[debug.log](https://github.com/user-attachments/files/17527374/debug.log)

**Comment by xiewuzhiying** [comment]
Fixed in [this commit](https://github.com/xiewuzhiying/VS-Addition/commit/21fcf876d9910cbebb2d8dace2a3d2481db845e1#diff-6eb61f161d9aab63afb57c2857be1c0378f26b0f0a10a6372b6e9b81f01ff472).I accidentally didn't push it as a separate commit.😥

**Comment by EndDragon438** [comment]
@xiewuzhiying is this a typo?
![image](https://github.com/user-attachments/assets/c2b6945c-b35a-4638-a2fd-3b53ca8f9bd4)
