### ISSUE TITLE
Game crashes because of portable fluid interface, not sure why or how.

### ISSUE THREAD

**Issue by CapiYT** [xiewuzhiying/VS-Addition#53]
### Mod Name

I'm not totally sure

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

I tried making a flying machine with several mods installed but it crashed randomly when I looked at the machine.

### Issue reproduction

I made a big flying machine with several props, I added a fluid tank which has to be refueled with a fluid interface. I used the flying machine a little bit, flew away and when I got down and looked at the bearing it crashed and continued to crash if I entered the world while looking at any part of the machine.

I took out the unnecessary mods like sodium or cc:tweaked and it didn't crash anymore.

### Logs

[crash-2024-10-28_13.00.22-server.txt](https://github.com/user-attachments/files/17545595/crash-2024-10-28_13.00.22-server.txt)

**Comment by xiewuzhiying** [comment]
It looks like you had the vmod installed and then removed it, causing the game to not find the ship attachments. You can try reinstalling it.
