### ISSUE TITLE
<title>Basin or Depot cannot absorb items when X or Z is negative in some cases

### ISSUE THREAD

**Issue by wuya-mkjy** [xiewuzhiying/VS-Addition#54]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

![L4~WB7A`@5P{G JUR32 AZP](https://github.com/user-attachments/assets/a5e4f44d-dd20-498e-904e-14bc2ca15bbf)

When the Basin or Depot has a negative X or Z position, I cannot throwing item on it. If several basins are put together, some of them can absorb items but some cannot. If the XZ postion is both positive, it works well.
I've tried in minecraft 1.20.1 with kotlinforforge 4.11.0, create 0.5.1h, vs 2.3.0, eureka 1.5.1 and VSA 0.0.7a. In this case the problem occurs.

> 

### Issue reproduction

case 1:Put basin or depot at negative X or Z position, then throw item to it. The item cannot be absorb if VSA is added.
case 2:Put several basins of depots together at negative X or Z position, then throw item to them. Some of the basins can aborb the items.

**Comment by xiewuzhiying** [comment]
Can't reproduce it, and also I don't think I've changed the code in issue.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/1.18.x/main/common/src/main/java/org/valkyrienskies/mod/mixin/mod_compat/create/MixinSharedDepotBlockMethods.java
I can't imagine why this issue is occurring.

**Comment by wuya-mkjy** [comment]
![Z92KFV9UBP17}7S_QQUQ0N](https://github.com/user-attachments/assets/37b28f67-fbb3-47b7-b84a-b2c23494749c)
![@IYWC@X F21%3NULE061S(5](https://github.com/user-attachments/assets/21cb056b-8031-408c-ae21-606acd33c7be)
The picture shows the difference between w. and wo. VSA.
I've record a video to reproduce the issue, but it exceeds the size limit of github, perhaps I can send it to you with QQ?

**Comment by wuya-mkjy** [comment]
![图片](https://github.com/user-attachments/assets/779f69d2-93c8-4ffb-9e76-3a6a190824c1)
I guess the problem is cause by floor?
When position of XZ is positive, it works as expected.
When the position of XZ is negative, the value is rounded beyond 0, perhaps a rounding to zero is expected behavior?

**Comment by wuya-mkjy** [comment]
https://github.com/user-attachments/assets/195af652-bb7d-48eb-903a-5f9578a8f561

I’ve compressed the video in 10M.

**Comment by wuya-mkjy** [comment]
The video can be played by VLC

**Comment by wuya-mkjy** [comment]
[视角交互修复vs_addition-1.20.1-0.0.7a+bf78e6dd60.jar.zip](https://github.com/user-attachments/files/17620173/vs_addition-1.20.1-0.0.7a%2Bbf78e6dd60.jar.zip)
I've found the problem. This issue only exist in this specified 0.07a version. It's different from the one released on github.
I just get it from the modpack.

**Comment by xiewuzhiying** [comment]
It looks like you'll have to ask your modpack author for help.
Or you can try switching to [CI build](https://github.com/xiewuzhiying/VS-Addition/actions) and see if it still has this issue?
