### ISSUE TITLE
能否用火炮外设直接获得火炮朝向

### ISSUE THREAD

**Issue by Cainiao1053Jr** [xiewuzhiying/VS-Addition#57]
能否增加火炮外设直接获取东南西北的朝向并返回？目前cc没法获取自己或者火炮的朝向，加上火炮本身物理化丢tag而丢失连接的bug，导致无法将自动攻击火控炮座放入自然生成并物理化。获取火炮或者电脑朝向以后可以使用命令方块规避火炮连接丢失的问题，从而实现自然生成敌对的瓦基载具并带有射界保护。并且替代目前先将火炮方块化再物理化获取方向的方法，并作为中介获取电脑的主世界坐标轴方向。

**Comment by xiewuzhiying** [comment]
有道理

**Comment by xiewuzhiying** [comment]
emmm...其实已经包含在`getYaw()`里了？

**Comment by Cainiao1053Jr** [comment]
getYaw这个能对空或者未组装火炮使用，但是在反复加载区块和重启电脑的情况下，二次开机需要先方块化火炮再组装，这有概率导致一些丢外设这样的bug，我加了启动延迟看上去解决了但不确定是否真的解决。直接获取方向可以规避。
