### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by thetheaplant** [xiewuzhiying/VS-Addition#61]
### Mod Name

cc-tweaked-1.20.1-forge-1.114.0

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

The game crashes as soon as a computer is loaded.

### Issue reproduction

Create a world, place a computer, it crashes.

### Logs

[crash-2024-11-16_12.13.26-server.txt](https://github.com/user-attachments/files/17787829/crash-2024-11-16_12.13.26-server.txt)
[latest.log](https://github.com/user-attachments/files/17787831/latest.log)

**Comment by xiewuzhiying** [comment]
It seems that some fields in Computer Craft classes have changed again, causing mixin errors. You can temporarily stay with the old version of Computer Craft (if there are no major feature updates in the new version).
