### ISSUE TITLE
在使用机械动力火炮附属时，船上的机炮开火声音不会播放

### ISSUE THREAD

**Issue by OC165** [xiewuzhiying/VS-Addition#62]
### Mod Name

Create Big Cannons

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

机炮在常规搭建时，开火声音正常播放。但将其建造于一艘物理化的船上时，开火的声音不会播放，仅有炮弹划过空气的声音。而且此问题仅存在于Create Big Cannons 5.5.0或更高版本，我想这可能与Create Big Cannons作者在5.5.0以及以后的版本中，修改了声音的传播方式，且Create Big Cannons作者发现了这一点，可见于
https://github.com/Cannoneers-of-Create/CreateBigCannons/issues/596
但其作者应该并不打算在Create Big Cannons永久修复这一点

### Issue reproduction

在安装有Valkyrien Skies和Create Big Cannons 5.5.0或更高版本的客户端中，将机炮搭建于一个已物理化的结构上并开火，开火声音不会播放。

**Comment by xiewuzhiying** [comment]
我在我的VS分支中修复了它，我忘记将它移入VS Addition。

**Comment by OC165** [comment]
> 我在我的VS分支中修复了它，我忘记将它移入VS Addition。

如果您能将其在下个版本的VS Addition中加入此功能的话 非常感谢您！

**Comment by xiewuzhiying** [comment]
将在下个版本中修复
