### ISSUE TITLE
<title>使用tacz枪械射击瓦尔基里物体极小概率引发时停(Too many physics frame)

### ISSUE THREAD

**Issue by WANGNIMA912** [xiewuzhiying/VS-Addition#64]
### Mod Name

Tacz,noisium,valkyrienskies

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

游戏前端没有崩溃，但是无法与世界后端交互

https://github.com/user-attachments/assets/f7c5c9be-759b-4426-812d-79fdabc05792

51秒后正片

### Issue reproduction

使用RPG射击瓦尔基里物体*边缘*

### Logs

[latest.log](https://github.com/user-attachments/files/17830431/latest.log)
[debug.log](https://github.com/user-attachments/files/17830432/debug.log)

**Comment by xiewuzhiying** [comment]
[vs_addition-1.20.1-0.0.9a+cdb0327b9e.jar.zip](https://github.com/user-attachments/files/17832657/vs_addition-1.20.1-0.0.9a%2Bcdb0327b9e.jar.zip)
尝试此构建是否能解决问题。

**Comment by WANGNIMA912** [comment]
已解决！这么快就修好是真的神仙
