### ISSUE TITLE
乘坐在瓦尔基里物体上时无法正常使用tacz枪械射击外界

### ISSUE THREAD

**Issue by WANGNIMA912** [xiewuzhiying/VS-Addition#66]
### Mod Name

tacz

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

https://github.com/user-attachments/assets/7aeea314-4365-4db2-bdf2-c7e8ade237a4

创建一个瓦尔基里物体，使用任意方法乘坐上去，使用tacz枪械射击外界

### Issue reproduction

同上，已在视频内展示

**Comment by MulatramAwA** [comment]
看起来不是VS-Addition的问题🤯
可能只能作为feature request
请您禁用VS-Addition后再次尝试复现👍

**Comment by xiewuzhiying** [comment]
它应该已经在最新版本（尚未推送的0.0.9a）中修复。

**Comment by WANGNIMA912** [comment]
https://files.catbox.moe/osblau.mp4
不行

**Comment by xiewuzhiying** [comment]
我试了一下，所有弹射物（包括原版弓箭）都有这种情况，我会想办法修一下。

**Comment by xiewuzhiying** [comment]
尝试解决了，但我做不到一次性让所有弹射物都兼容，有其他模组不兼容的欢迎提issue。
