### ISSUE TITLE
CC:C Bridge animatronic incompatability (related to embeddium)

### ISSUE THREAD

**Issue by Electric131** [xiewuzhiying/VS-Addition#68]
### Mod Name

CC:C Bridge / Embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Not exactly sure if this counts as a compatability issue with vs-addition but having vs-addition and embeddium seems to cause rendering issues when a CC:C Bridge animatronic is placed on a ship despite working in older versions of vs-addition.

When placing the CC:C Bridge animatronic on a ship, only its base is rendered instead of its full body. In earlier versions of vs-addition (testing as recent as v0.0.8) the animatronic renders correctly however upon upgrading to v0.0.9 or later the rendering breaks.

At first I thought this rendering issue was simply vs-addition and CC:C bridge but it seems like the issue only happens when embeddium is also present as well as newer versions of vs-addition. I understand it may be hard to pinpoint why the newer version of this mod break something with CC:C bridge or embeddium but I figured I would make a report anyway.

### Issue reproduction

Launch the game with CC:C bridge, its dependencies, embeddium, and vs-addition 0.0.9. Create a ship and place the CC:C Bridge animatronic on it. Observe the base is the only part that renders. (Next part is optional to confirm it does work in earlier versions even with embeddium or new version without embeddium) Close the game and downgrade to vs-addition v0.0.8 and repeat the previous steps, observing that the animatronic correctly renders. Then close the game, upgrade vs-addition back to v0.0.9 and uninstall embeddium.

**Comment by xiewuzhiying** [comment]
I added a config item to resolve it, you can get the latest build at Github Actions
