### ISSUE TITLE
建议增加小型船舶制造器

### ISSUE THREAD

**Issue by Misaka2298** [xiewuzhiying/VS-Addition#7]
如题，原版的瓦尔基里有一个小型船舶制造器（附魔小木棍），使用它可以制造缩小的瓦尔基里船，但是这样难以批量生产缩小的瓦尔基里船结构（如机载导弹）。
所以建议增加一个类似船舵和Tournament物理化方块的小型船舶制造器，右击该方块后就会像使用船舵物理化一样自动识别与其连接的方块并将他们一起物理化为小型瓦尔基里船。

**Comment by shuangfas** [comment]
不如直接加个可以控制船大小的方块

**Comment by xiewuzhiying** [comment]
你只需使用[Vmod](https://modrinth.com/mod/vmod)
