### ISSUE TITLE
Fails to boot when Create Crafts & Additions is installed

### ISSUE THREAD

**Issue by Draconad** [xiewuzhiying/VS-Addition#8]
### Mod Name

Create Crafts & Additions

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

Client wont boot when Create Crafts & Additions is installed. It seems ot be related to their portable energy interface?
Also Im on Fabric 1.20.1, but the above option only allows me to select up to 1.19

### Issue reproduction

Install Create Crafts & Additions along with this mod

### Logs

[crash-2024-06-26_15.01.14-client.txt](https://github.com/user-attachments/files/15990389/crash-2024-06-26_15.01.14-client.txt)

**Comment by xiewuzhiying** [comment]
Actually I shouldn't have added `remap = false`
Will be fixed in the next version.

**Comment by xiewuzhiying** [comment]
Sorry for the two-week delay.
